### ISSUE TITLE
Categories and budget allocation view

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-rf6#2]
As a user, I want to see the last of the categories to decide on delegation or voting. 
As a user, I want to have some CTAs for connecting to WorldID and Farcaster
As a user, I want to have a CTA to update my ballot on voting UI. 

### Design and User Flow
https://www.figma.com/design/tP7Arb2C8aDB05wCVxVVSB/Pairwise-RF6--%3E-Voting-App?node-id=865-70829&t=iSsVXOP4qNd9hqmr-4

### Success Criteria

**1-General**
- [x] There are 4 categories in which the `Budget` category has different Voting experience. It should load [Budget Allocation](https://www.figma.com/design/tP7Arb2C8aDB05wCVxVVSB/Pairwise-RF6--%3E-Voting-App?node-id=946-39240&t=iSsVXOP4qNd9hqmr-4) view.
- [x] The budget category does not have any `projects number` badge.
- [x] Delegate will load the Farcaster delegate flow. #3 
- [x] Vote will load the pairwise comparisons flow if connected by email. #5 #4 
- [x] Voted categories should not be able to be delegated
- [x] Delagated categories should not be able to be voted. 
- [x] Voted categories can be edited manually and attested again. #6 

- [x] **2- Voted categories** has 
1- edit and view attestation CTAs, 
2- green border and `voted badge`
3- they can have the `n people delegated to you` badge if connected to Farcaster/X

- [x] **3- Delegated Categories** has 
1- a `delegated to @handler` 
2- a `revoke` CTA, which revokes the delegation and changes the status. 
3- they are grayed out 
4- they can have the `n people delegated to you` badge if connected to Farcaster/X

- [x] **4-** Clicking on a vote on the Budget category will show the **Budget allocation view** with a slider and percentages on each category. 
0- check if connected with email #4 then load the page
1- The slider can change the OP amount
2- Percentages can be locked, only one of them can be locked at the same time, if any are locked, the other will be disabled. 
3- when changing any % the other will change accordingly based on the weights they have (it's not equal raise/deficit if more than one is unlocked) 
4- if the user ends up having more than 100% in summation, a toast message shown accordingly
5- The back button will lead the user back to categories. 
6- Submit vote will load the attestation flow. 

- [x] **5- Your voting power** box, it shows the badges, and has a worldID button, which is different when connected. (remove X for first version)

- [x] **6- Claim more voting box** It shows the connect with Farcaster and X button, and has a different view when any of them connected.  (remove X for the first version)

- [ ] #37 

- [ ] #15
- [x] #16
