### ISSUE TITLE
Pairwise comparisons with stars and undo

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-rf6#5]
As a user, I want to compare projects in a fun way to curate and rank the projects.

### Design:
https://www.figma.com/design/tP7Arb2C8aDB05wCVxVVSB/Pairwise-RF6--%3E-Voting-App?node-id=1175-35869&t=5fs3dq4aACc9dvJA-4

### Acceptance Criteria

- [x] 1- Check whether is user has an aa wallet and signed in with Thirdweb or not, if not run the #4 
- [x] 2- The user will be guided by a modal to know they vote on behalf of these numbers of people delegated to them. 
- [x] 3- **Flow is Like RF5:**

3.1- Category and the question in the header. 
3.2 projects cards- tiny change of having links in "grants and investments"
3-3 Undo
3-4 conflict of interest
3-5 Stars
3-6 progress bar
3-7 Guidance modals (how to put starts and avoid selecting a lower-ranked project) 
3-8 AI Summary

- [ ] 4- After the user is ranked we will show the results and let the user edit and save changes. (Edit ACs are in #6 ) - Note that ranked are open to edit when they see the results. 
- [ ] 5- When the user clicks on `submit vote` app will run the attestation flow #9

**Comment by maryjaf** [comment]
- [ ] 1- testimonial links are broken. 

The correct format is:
https://www.metricsgarden.xyz/projects/0x4d7ac580e10414ef62d024b14ad94ebd1434efacd1fd3f453560b2916f2606d2/?tab=insights
For this project:
https://develop-op-rf-6.up.railway.app/project/0xab39b725ae275ff8055702e58441f053d71967ffc9686ec9201bba813b301c67



- [ ] 2- These are descriptionsm not metrics 
[Impact Garden - Attest Fest](https://www.metricsgarden.xyz/projects/0x4d7ac580e10414ef62d024b14ad94ebd1434efacd1fd3f453560b2916f2606d2/?tab=insights)
[Retro Funding 6: Voting](https://develop-op-rf-6.up.railway.app/project/0xab39b725ae275ff8055702e58441f053d71967ffc9686ec9201bba813b301c67)

for 2:

![Image](https://github.com/user-attachments/assets/4c950016-9830-4d96-b522-ea1b5b6bb775)


- [ ] 3- Strange flashing in header:

https://www.loom.com/share/883817aad5d94ef1bb56e8e98746fd8b


@Meriem-BM

**Comment by Meriem-BM** [comment]
@maryjaf can you check this please

**Comment by MoeNick** [comment]
I tested and it was working fine.

**Comment by MoeNick** [comment]
Flashing has been solved, and impact garden is also solved, just some small items:
- [ ] 3- github icon is not showing completely on my end. ![Image](https://github.com/user-attachments/assets/13b26b20-dc93-4d57-bbd5-d8b8aaf1a9ce)
- [ ] 4- Some links in Github sections does not have title. 
It should be like: with  a title linked to a hyper link and description when opened. 
![Image](https://github.com/user-attachments/assets/f89b9a29-996f-47a4-87d0-02f930b71139)

But it's showing: 
![Image](https://github.com/user-attachments/assets/820fcd69-82d6-496a-b76e-6ada6e824a1b)

the screenshots taken from this project if you want to check: https://develop-op-rf-6.up.railway.app/project/0x0176ac7bcd9e5f6f9ac3b8d3cbeae9055d9d0ec651f2e151734e15444c95c0cc

Thanks @Meriem-BM
